requestRouter:
  port: 8080
  name: prestoRouter
  historySize: 1000

dataStore:
  jdbcUrl: jdbc:mysql://presto-gateway-rds.moeinternal.com:3306/prestogateway
  user: SQL_USERNAME
  password: SQL_PASSWORD
  driver: com.mysql.cj.jdbc.Driver

server:
  applicationConnectors:
    - type: http
      port: 8090
  adminConnectors:
    - type: http
      port: 8091

notifier:
  smtpHost: localhost
  smtpPort: 587
  sender: presto-gw-monitor-noreply@lyft.com
  recipients:
    - prestodev@yourorg.com

pagerduty:
  integrationKey: a22d1cfc9f6b494bae6452fc31bcb6f3
  env: prod
  region: ap-south-1

modules:
  - com.lyft.data.gateway.ha.module.HaGatewayProviderModule
  - com.lyft.data.gateway.ha.module.ClusterStateListenerModule
  - com.lyft.data.gateway.ha.module.NotifierModule

managedApps:
  - com.lyft.data.gateway.ha.GatewayManagedApp
  # - com.lyft.data.gateway.ha.clustermonitor.ActiveClusterMonitor

# Logging settings.
logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:
    com.lyft: DEBUG

  appenders:
    - type: console
    - type: file
      currentLogFilename: /var/log/prestoproxy/prestoproxy-java.log
      archivedLogFilenamePattern: /var/log/prestoproxy/prestoproxy-java-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 100MB
